title: Weston Westenborg
brand: Weston Westenborg
description: Writing and projects from Weston Westenborg, co-founder of allUP.
url: https://westenb.org
author:
  name: Weston Westenborg
  url: https://westenb.org/about/

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - ruby
  - vendor
  - docs
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
