title: westenb.org
brand: Weston Westenborg
description: Personal website and blog
url: https://westenb.org
author:
  name: Weston Westenborg

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - ruby
  - vendor
  - docs
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-feed